server.port: 8084

solon.app:
  name: demoapi4
  group: demo

server.session:
  timeout: 7200 #单位秒；（可不配，默认：7200）
  state:
    jwt:
      name: TOKEN #变量名；（可不配，默认：TOKEN）
      secret: "E3F9N2kRDQf55pnJPnFoo5+ylKmZQ7AXmWeOVPKbEd8=" #密钥（使用 JwtUtils.createKey() 生成）；（可不配，默认：xxx）
      allowExpire: true #充许超时；（可不配，默认：true）；false，则token一直有效
      allowIssue: false #充许输出；（可不配，默认：true）；flase，则不向header 或 cookie 设置值（由用户手动控制）
      allowUseHeader: false #充许使用Header传递；（可不配，默认：使用 Cookie 传递）；true，则使用 header 传递

demo.cache1:
  server: redis.water.io:6379
  user: redis
  password: 123456


demo.db1:
    schema: rock
    jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456