server.port: 8084

solon.app:
  name: demoapi4
  group: demo

server.session:
  timeout: 300 #s
  state:
    jwt:
      name: TOKEN #变量名；（可不配，默认：TOKEN）
      secret: "E3F9N2kRDQf55pnJPnFoo5+ylKmZQ7AXmWeOVPKbEd8=" #密钥（使用 JwtUtils.createKey() 生成）；（可不配，默认：xxx）
      allowExpire: true #充许超时；（可不配，默认：true）
      allowIssue: true #充许输出；（可不配，默认：true）
      allowUseHeader: true #充许使用Header传递；（可不配，默认：使用 Cookie 传递）

demo.cache1:
  server: redis.water.io:6379
  user: redis
  password: 123456


demo.db1:
    schema: rock
    jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456